
(function($)
{'use strict';$.fn.fancy=function(options)
{options=$.extend({},_$('$.jet.services.fancybox')._.options,$.fn.fancy.defaultOptions,options);var self=this;typeof $.fn.fancybox==='function'?self.fancybox(options):$(document).on('fancyboxLoaded',function(){self.fancybox(options);});return this;};$.fancy=$.fn.fancy;$.fn.fancy.defaultOptions={};}(jQuery));ajax_upload={frame:function(c){var n='f'+Math.floor(Math.random()*99999);var d=document.createElement('DIV');d.innerHTML='<iframe style="display:none" src="about:blank" id="'+n+'" name="'+n+'"></iframe>';document.body.appendChild(d);$("#"+n).on('load',function(){ajax_upload.loaded(n);});var i=document.getElementById(n);if(c&&typeof(c.onComplete)=='function'){i.onComplete=c.onComplete;}
return n;},form:function(f,name){f.setAttribute('target',name);},submit:function(f,c){ajax_upload.form(f,ajax_upload.frame(c));return(c&&typeof(c.onStart)=='function')?c.onStart():true;},loaded:function(id){var i=document.getElementById(id),d;d=i.contentWindow?i.contentWindow.document:i.contentDocument?i.contentDocument:i.document;if(d.location.href=="about:blank"){return;}
if(typeof(i.onComplete)=='function'){var ret=(null===d.body.innerHTML.match(/^<pre.*<\/pre>$/i))?d.body.innerHTML:d.documentElement.textContent;i.onComplete(ret);}}}
ccmBoxes=window.ccmBoxes||{boxes:{}};ccmBoxes.topic=(function($){"use strict";return{question_id:0,forum_id:0,get_prms:{},uforum:{},container:null,imageUploaded:false,msgs:{show_cmts:'',hide_cmts:'',post_error:'',solve_lnk:'',unsolve_lnk:''},messages:{start_upload:"Processing ...",ok_upload:"Done !",error:"Request error"},urls:{prefix:'/forum/_xhr_/',pmm:'/forum/_xhr_/postmodomenu/'},constants:{CCM_MSG_QUESTION:1,CCM_MSG_QUESTION_COMMENT:2,CCM_MSG_ANSWER:3,CCM_MSG_ANSWER_COMMENT:4},_is:{cim:0,frmqa_init:false,msgrsz:null},topicfrms:{},init:function(question_id,w_qa_evt){var _abm=this.abm,_res=null,_matchResult=null;this.question_id=question_id;this.container=$('#ctn_'+question_id);if(this.container.length===0){return false;}
_res=this.initEvents();var $msg=$('#message');if(_res&&w_qa_evt){_res=this.initQafrmEvents($msg);}
_matchResult=window.document.URL.match(/#newanswer$/);if(_matchResult){_abm.loadFrm('newa',this.question_id,this.question_id);location.hash='';}
_matchResult=window.document.URL.match(/#.*?(new|edit)(q|a|c)_(\d+)_(\d+)_(\d)/);if(_matchResult&&_matchResult.length===6){this._is._cur_star=_matchResult[5]||false;_matchResult[3]=parseInt(_matchResult[3],10)||this.question_id;_matchResult[4]=parseInt(_matchResult[4],10)||this.question_id;_abm.loadFrm(_matchResult[1]+_matchResult[2],_matchResult[3],_matchResult[4]);location.hash='';}
this.uforum.get_prms=(this.uforum.module?'&ufmodule='+encodeURIComponent(this.uforum.module):'')
+(this.uforum.info_id?'&ufinfoid='+this.uforum.info_id:'')
+(this.uforum.title?'&uftitle='+encodeURIComponent(this.uforum.title):'')
+(this.uforum.info_url?'&ufurl='+encodeURIComponent(this.uforum.info_url):'')
+(this.uforum.info_aid?'&ufaid='+encodeURIComponent(this.uforum.info_aid):'')
+(this.uforum.info_anick?'&ufanick='+encodeURIComponent(this.uforum.info_anick):'')
+(this.uforum.info_atok?'&ufatok='+encodeURIComponent(this.uforum.info_atok):'')
+(this.get_prms.tcp?'&tcp='+encodeURIComponent(this.get_prms.tcp):'');$('#jFormSearchOptionsClose').on('click',function(){$('#jSearchOptions').css('display','none');return false;});$('.jSearchOptionsShow').on('focus',function(){$('#jSearchOptions').css('display','block');});return _res;},initEvents:function(){var $mdn=$('#modo_div_new');if(this.container.length===0){return false;}
var $container=$(this.container[0]);$container.on('click','.jStarNote',this.clickOnStarComment).on('click','.JDisplayCommentFromVote',this.displayVoteComment).on('click','.jOpenSignalPopup',this.openSignalPopup.bind(this)).on('click','.jShowImgOnlyForMember',this.displayImgOnlyForMemberWarning).on('click','.jInsertPic',this.insertPic.bind(this)).on('click','.jMeToo',this.meToo.bind(this)).on('click','.jSeeMorePoc',this.seeMorePoc.bind(this));ccm.common.event.on(this.container[0],'click',this.onClick,this,true);ccm.common.event.on(this.container[0],'dblclick',this.onDblClick,this,true);ccm.common.event.on(this.container[0],'focus',this.onFocus,this,true);ccm.common.event.on(this.container[0],'blur',this.onBlur,this,true);if($mdn.length>0){ccm.common.event.on($mdn[0],'click',this.onClick,this,true);ccm.common.event.on($mdn[0],'focus',this.onFocus,this,true);ccm.common.event.on($mdn[0],'blur',this.onBlur,this,true);}
$mdn=$('#newqcmt');if($mdn.length>0){ccm.common.event.on($mdn[0],'click',this.onClick,this,true);}
$mdn=$('#newqcmt_bottom');if($mdn.length>0){ccm.common.event.on($mdn[0],'click',this.onClick,this,true);}
$mdn=$('#stars_digest_eval');if($mdn.length>0){ccm.common.event.on($mdn[0],'click',this.onClick,this,true);}
$(this).checkNicknameAnon();$(this).checkEmailAnon();return true;},openSignalPopup:function(event){event.preventDefault();var $targetDiv=$(event.target),msgId=$targetDiv.data('msgid'),actId=$targetDiv.data('actid')||'signal',$ctnfrm=$('#modo_div_new'),targetOffset=$targetDiv.offset();if($ctnfrm.length===0){return false;}
if(this._is.cim>0){$ctnfrm.css('display','none').html('');if((this._is.cim===msgId)||$targetDiv.hasClass('jCloseModoMenu')===true){this._is.cim=0;return false;}}
this.mod.place(targetOffset.top+','+targetOffset.left);$ctnfrm.html('&nbsp;').css('display','block');this._is.cim=msgId;this.mod.load(msgId,actId,null,'');},displayVoteComment:function(event){event.preventDefault();$('#comments_'+$(event.target).data('msgid')+' .jCommentItem').show();},displayImgOnlyForMemberWarning:function(event){event.preventDefault();$(event.target).closest('form').find('.jImgOnlyForMember').show();},insertPic:function(event){event.preventDefault();var $form=$(event.target).closest('form'),$element=$form.find('.jSubmitImg');if($element.length>0&&$element.hasClass('onChangeSpecified')===false){$element.on('change',this.startUpload.bind(this)).addClass('onChangeSpecified');}
ccm.contents.utils.elts.opts_form=$form[0];ccm.contents.utils.elts.textarea=($form.find('.jTextareMessage'))[0];$element.trigger('click');},meToo:function(event){let url='/api/forum/v1/metoo',$target=$(event.target),$value=$('.value-total-metoo'),$data;let token=$target.attr('data-token');if(typeof token!=='undefined'&&token!==false){$data={topicId:$target.attr('data-id'),cryptedToken:$target.attr('data-token')};}else{$data={topicId:$target.attr('data-id')};}
$.ajax({url:url,type:'POST',data:$data,success:function(){$target.addClass('btn--active');if(!isNaN(parseInt($value.text()))){$value.text(parseInt($value.text())+1);}else{$(event.target).html($(event.target).text()+" (<span class='value-total-metoo'>1</span>)")}
return true;},error:function(response){if(response.status==409){$target.removeClass('btn--active');if(!isNaN(parseInt($value.text()))){$value.text(parseInt($value.text())-1);}else{$(event.target).html($(event.target).text()+" (<span class='value-total-metoo'>0</span>)")}}
return true;},});},seeMorePoc:function(event,anchor,callback){var _ct=ccmBoxes.topic,msgid=$(event.target).attr('data-msgid'),parentx=$(event.target).attr('data-parentx');var $overlayDiv=$('.jOverlay');$overlayDiv.addClass('overlay-display');$.ajax({url:_ct.urls.prefix+'showallanswercomments/?msgid='+msgid+'&parentx='+parentx,data:'',type:'GET',async:false,success:function(data){$(event.target).closest('div .for_answer__comments').html(data);if(typeof anchor!=="undefined"){callback(anchor);}else{var $elem=$("#comments_"+msgid);if($elem.length>0){$.fn.scrollToElem($elem);}}},complete:function(){$overlayDiv.removeClass('overlay-display');},});},clickOnStarComment:function(event){event.preventDefault();var $target=$(event.target),starValue=$target.attr('actnum')||false,$form=$target.parents('form'),$currentNote=$target.siblings('.jCurrentNote');if(starValue&&$form.length>0&&$currentNote.hasClass('currentNote')){$form.find('input:hidden[name=stareval]').val(starValue);$currentNote.css('width',(16*parseInt(starValue,10))+'px');$form.find('[name=message]').first().trigger('focus');}},initModoEvents:function(){var $modSelact=$('#mod_selact');if($modSelact.length>0){ccm.common.event.on($modSelact[0],'change',this.onChange,this,true);}},initQafrmEvents:function($el){if($el.length===0){return false;}
(new ccm.common.dom.TaResize($el)).go();$el=$('#icnbar');if($el.length>0){ccm.common.event.on($el[0],'mouseover',this.onMouseOver,this,true);ccm.common.event.on($el[0],'mouseout',this.onMouseOut,this,true);}
this._is.frmqa_init=true;return true;},initQuestionEvents:function(){var $el=$('#topic_question');if($el.length===0||$el.html()===''){return false;}
ccm.common.event.on($el[0],'dblclick',this.onDblClick,this,true);return true;},getCommonPrms:function(exclude_cat){var cat='';if(!exclude_cat){cat='&cat='+this.forum_id;}
return'parentx='+this.question_id+cat+(this.get_prms.s?'&s=s':'')+this.uforum.get_prms;},startUpload:function(){var self=this,_ret=ajax_upload.submit(ccm.contents.utils.elts.opts_form,{onStart:function(){return ccm.contents.utils.callbackStartUpload(self.messages.start_upload);},onComplete:function(responseText){ccm.contents.utils.callbackOnCompleteUpload(responseText,self.messages);}});if(_ret){ccm.contents.utils.elts.opts_form.submit();}},reloadTopic:function(stopLoader=false){var self=this;ccm.common.dom.oldAjaxUpdater(this.container,this.urls.prefix+'fulltopic/',{method:'get',parameters:this.getCommonPrms(true)+'&ID='+this.question_id+(this.get_prms.sort?'&sort='+this.get_prms.sort:'')+'&page='+this.get_prms.page+(this.get_prms.full?'&full':''),evalScripts:true,onComplete:function(){self.topicfrms=[];self.abm.mode='';self._is.cim=0;$('#modo_div_new').css('display','none');if(stopLoader)
{$('.jLoaderBouncing').removeClass('loader-bouncing--display');}},onFailure:function(){if(stopLoader)
{$('.jLoaderBouncing').removeClass('loader-bouncing--display');}}});},getMsgId:function($el,qa_only){var _m=null,$body=$('body');while($el!==null&&$el.length>0&&$el!==$body){if(typeof $el.attr("id")!=="undefined"){_m=(qa_only)?$el.attr("id").match(/^(a|ctn_)(\d+)$/):$el.attr("id").match(/^(a|c|ctn_|f)(\d+)$/);}
if(_m){return parseInt(_m[2],10);}
if($el.attr("id")==='frmactmod'){_m=(qa_only)?$el[0].parent.value:$el[0].ID.value;if(_m){return parseInt(_m,10);}}
$el=$el.parent();}
return 0;},triggerErrorInEl:function($el,msg){if($el.length===0||!msg){return;}
$el.css('display','block');$el.removeClass().addClass('form_errors_list');$el.html(msg);},triggerOkInEl:function($el,msg){if($el.length===0){return;}
$el.css('display','');if(msg){$el.removeClass().addClass('ftGreen radius5 marB5');$el.html(msg);}},checkJson:function(json,$el){if(!json.res&&json.msgs){var _s='';for(var i=0;i<json.msgs.length;i++){_s+='<li>'+((json.msgs[i]instanceof Array)?json.msgs[i][1]:json.msgs[i])+'</li>';}
_s=(_s==='')?json.msg:'<ul class="disc">'+_s+'</ul>';this.triggerErrorInEl($el,_s);return false;}
return true;},onClick:function(event){var _ret=false,_gei=ccm.common.event.getEventInfos(event),$tgt=$(_gei[0]),_actid=_gei[1],_msg_id=0,_ctnfrm,_parent_id,self=this,_abm=self.abm,_docu=null,_href=null,_mode='',$el=null,csrf_token=null,_acttype='',_force_txt='',_ta='';if(_actid==='ofempty'){return true;}
if(_actid){_msg_id=this.getMsgId($tgt,false);}
else if($tgt.length>0&&$tgt.prop('tagName')==='A'&&typeof $tgt.prop('hash')!=='undefined'&&typeof $tgt.attr('href')!=='undefined'&&$tgt.attr('href').length>0){_docu=window.document.URL.replace(/#.*$/,'');_href=$tgt.attr("href").replace(/#.*$/,'');if(_href.match(/itunes\.apple\.com\//)){$tgt.attr("href",_href+'&at=1l3v7Mj&ct=appstv');}
return(_docu===_href)?ccm.common.dom.scroll.go($tgt):true;}else{if($tgt.attr("href")&&$tgt.prop("tagName")==='A'&&$tgt.attr("href").match(/itunes\.apple\.com\//)){$tgt.attr("href",$tgt.attr("href")+'&at=1l3v7Mj&ct=appstv');}
return true;}
_mode=$tgt.attr('mode')||false;switch(_actid){case'shlog':_ctnfrm=$tgt.parent().parent();if(_ctnfrm.length>0&&(_ctnfrm.hasClass("login"))){_ctnfrm.css('display','none');$el=_ctnfrm.next();while($el.length>0&&$el.prop("tagName")!=='DIV'){$el=$el.next();}
$el.show();}
break;case'hilog':_ctnfrm=$tgt.parent().previous();while(_ctnfrm.length>0&&_ctnfrm.prop("tagName")!=='DIV'){_ctnfrm=_ctnfrm.prev();}
if(_ctnfrm.length>0&&(_ctnfrm.hasClass('login'))){_ctnfrm.css('display','block');$el=_ctnfrm.next();while($el.length>0&&$el.prop("tagName")!=='DIV'){$el=$el.next();}
$el.hide();}
break;case'shcmts':$tgt.parent().hide();$('#comments_'+_msg_id).find(".jCommentItem").each(function(){$(this).show();$(this).parent('[style*="none"]').show();});break;case'shcmtfrm':_ret=true;_parent_id=this.getMsgId($tgt,true);_abm.loadFrm(_mode||'newc',_msg_id,_parent_id);break;case'newqcmt':_ret=$tgt.hasClass('jBtnNextHide');this._is._cur_star=$tgt.attr('actnum')||false;_abm.loadFrm(_mode||'newc',this.question_id,this.question_id);document.getElementById('simili_container').parentNode.insertBefore(document.getElementsByClassName('jSimiliInsert')[0],document.getElementById('simili_container').nextSibling);break;case'cancelcmt':_parent_id=this.getMsgId($tgt,true);if(_mode.search(/^edit/)>=0){_abm.reloadOri(_mode,_msg_id,_parent_id);}
_abm.closeFrm(_mode||'newc',_msg_id,_parent_id);break;case'postcmt':case'pviewcmt':_parent_id=this.getMsgId($tgt,true);_abm.submitFrm(_mode||'newc',_msg_id,_parent_id,(_actid==='pviewcmt'));break;case'shqafrm':_ret=true;_abm.loadFrm(_mode||'newa',_msg_id,this.question_id);break;case'cancelqa':if(_mode.search(/^edit/)>=0){_abm.reloadOri(_mode,_msg_id,this.question_id);}
_abm.closeFrm(_mode||'newa',_msg_id,this.question_id);break;case'postqa':case'pviewqa':_abm.submitFrm(_mode||'newa',_msg_id,this.question_id,(_actid==='pviewqa'));break;case'backedit':_abm.toggleDisplay(_mode||'newa','none',_msg_id);break;case'addmyi':_ret=true;case'shmodomenu':case'solve':case'pharos_warn':case'pharos':_ctnfrm=$('#modo_div_new');if(_ctnfrm.length===0){return false;}
var prms='';if(self._is.cim>0){if(_actid.match(/pharos/)){prms='act='+_actid+'&token='+$('#frmactmod').find('input[name="token"]').val();}
_ctnfrm.css('display','none').html('');if((!_actid.match(/solve|addmyi|pharos/)&&(self._is.cim===_msg_id))||$tgt.hasClass('jCloseModoMenu')===true){self._is.cim=0;return false;}}
if(!_actid.match(/pharos/)){self.mod.place(event);}
_ctnfrm.html('&nbsp;').css('display','block');self._is.cim=_msg_id;self.mod.load(_msg_id,_actid,null,prms);break;case'votep':case'votem':_ret=true;_ctnfrm=$('.jVote[data-voteid="'+_msg_id+'"]');csrf_token=_ctnfrm.data('token');if(_ctnfrm.length===0){return false;}
_ctnfrm.html('&nbsp;').addClass('waiting');$.ajax({url:self.urls.prefix+'vote/',data:self.getCommonPrms()+'&ID='+_msg_id+'&vote='+_actid+'&token='+csrf_token,type:'GET',success:function(data){_ctnfrm.html(data);$('#shcmts'+_msg_id).trigger('click');_ctnfrm.removeClass('waiting');},error:function(){_ctnfrm.removeClass('waiting').html('ERR');}});break;case'reloadtopic':this.reloadTopic();break;case'textfmt':_acttype=$tgt.attr('acttype')||false;if(!_acttype){return true;}
_force_txt=(_acttype==='conf')?$tgt.attr("title"):false,_ta=$tgt.parent().parent().attr('taid')||'message';ccm.contents.wikiEditor.insertTag("#"+_ta,_acttype,true,false,_force_txt);break;case'manual_upload_pic':this.startUpload();case'insertpic':$el=$('#filename_frm');if(!this.imageUploaded){this.imageUploaded=true;if($el.length>0){ccm.common.event.on($el[0],'change',self.onChange,self,true);}}
ccm.contents.utils.elts.opts_form=_abm.getFrm(_mode,_msg_id)[0];ccm.contents.utils.elts.opts_form.action='/forum/_xhr_/uploadimg/';ccm.contents.utils.elts.textarea=$('#message')[0];$el.trigger('click');break;case'showdsclmr':$('#dsclmr').toggle();break;case'modnewreason':var $tareason=$("#tareason");if($tareason.length>0){$tareason.val($tareason.val()+"* "+$tgt.attr('title')+"\n\n");$tgt.css('color','#FD981E');}
break;case'modsubmit':this.mod.submit(_msg_id);break;default:_ret=true;break;}
return _ret;},onBlur:function(event){return ccm.common.event.getEventInfos(event)[1]!=='author';},onMouseOver:function(event){var	_gei=ccm.common.event.getEventInfos(event),$tgt=$(_gei[0]);if(_gei[1]==='textfmt'){ccm.contents.wikiEditor.tooltip.show($tgt.attr('actlbl')||$tgt.attr("title")||'',true);}
return true;},onMouseOut:function(event){if(ccm.common.event.getEventInfos(event)[1]==='textfmt'){ccm.contents.wikiEditor.tooltip.hide();}
return true;},onChange:function(event){var _gei=ccm.common.event.getEventInfos(event),$tgt=$(_gei[0]);switch(_gei[1]){case'upload_pic':this.startUpload();break;case'mod_selact':this.mod.load(this.getMsgId($tgt,false));break;default:return true;}
return false;},onDblClick:function(event){var _gei=ccm.common.event.getEventInfos(event),$tgt=$(_gei[0]),_actid=_gei[1],_msg_id=0,_mode=$tgt.attr('mode')||false,_abm=ccmBoxes.topic.abm,_parent_id='';if(_actid){_msg_id=this.getMsgId($tgt,false);}else{return true;}
switch(_actid){case'shqafrmdc':case"shqafrmdcq":_abm.loadFrm(_mode||'editq',_msg_id,this.question_id);this._is.titlefocus=($tgt.attr("id")==='qtitle');break;case'shcmtfrmdc':_parent_id=this.getMsgId($tgt,true);_abm.loadFrm(_mode||'edicc',_msg_id,_parent_id);break;}
return false;},abm:{mode:'',getFrmCtn:function(mode,msg_id,parent_id){switch(mode){case'newa':return $('#newanswer_ctn');case'newq':case'editq':return $('#editques_ctn');case'newc':return $('#g'+parent_id);case'editc':case'edita':return $('#e'+msg_id);}},getFrm:function(mode,msg_id){switch(mode){case'newa':case'edita':case'newq':case'editq':return $('#frmqa');case'newc':case'editc':return $('#f'+msg_id);}},toggleOvlDisplay:function(mode,dispState,msg_id,parent_id){var $el;switch(mode){case'newa':$el=$('#newanswer_ovl');break;case'newc':var $cmtBest=$('#addCommentBest');$cmtBest.removeClass('hidden');case'editq':$el=$('#o'+parent_id);break;case'editc':case'edita':$el=$('#o'+msg_id);break;default:return;}
$el.css('display',dispState);},toggleOvlFrm:function(mode,dispState,msg_id){var $el=ccmBoxes.topic.abm.getFrm(mode,msg_id),$wd=null;if($el.length>0){$wd=$el.nextAll('div').eq(0);$wd.css('display',dispState);$el=$el.parent().find('textarea').eq(0);$el.prop('disabled',($wd.css('display')!=='none'));}},toggleEditor:function(mode,force,msg_id,parent_id){var $el=$('#a0'),$frmctn=null;$el.remove();switch(mode){case'newa':$el=$('#newanswer_'+ccmBoxes.topic.question_id);$el.css('display',force);if(force==="block"){$('.jReplyDisplayBtnBar').hide();}else{$('.jReplyDisplayBtnBar').show();}
break;case'newq':case'editq':$el=$('#ctnedtmsg');$el.css('display',force);break;case'editc':case'edita':$el=$('#e'+msg_id);$el.css('display',force);break;case'newc':$frmctn=ccmBoxes.topic.abm.getFrmCtn(mode,msg_id,parent_id);if($frmctn.length>0){$el=$frmctn.parent().find('form').eq(0);if(force==='none'){if($el.length>0){$el.css('display','block');}else{$frmctn.parent().css('display','none');}}else{$el.css('display','none');$frmctn.css('display','block');$frmctn.parent().css('display','block');}}
break;}},closeFrm:function(mode,msg_id,parent_id){var _abm=ccmBoxes.topic.abm,$frmctn=null;_abm.toggleEditor(mode,'none',msg_id,parent_id);_abm.toggleDisplay(mode,'block',msg_id);switch(mode){case'newa':$('#a0').remove();break;case'newc':$('#c0').remove();break;}
$frmctn=_abm.getFrmCtn(mode,msg_id,parent_id);$frmctn.html('');_abm.mode='';},isOkForEdit:function(mode,msg_id,parent_id){var _abm=ccmBoxes.topic.abm,selfMode=_abm.mode,selfCurMsgId=_abm.cur_msg_id,selfCurParentId=_abm.cur_parent_id,$frmctn=null;switch(mode){case'newa':case'newq':case'edita':case'editq':if(selfMode){if(selfMode===mode&&selfCurMsgId===msg_id){_abm.gotoEditor(mode);return false;}
$frmctn=_abm.getFrmCtn(selfMode,selfCurMsgId,selfCurParentId);if($frmctn.length>0&&$frmctn.html()!==''){_abm.closeFrm(selfMode,selfCurMsgId,selfCurParentId);}}
_abm.mode=mode;_abm.cur_msg_id=msg_id;_abm.cur_parent_id=parent_id;}
return true;},loadFrm:function(mode,msg_id,parent_id){var _abm=ccmBoxes.topic.abm,$ctnfrm=_abm.getFrmCtn(mode,msg_id,parent_id),_url=((mode==='newc')||(mode==='editc'))?'shcmtfrm/':'shqafrm/',_ct=ccmBoxes.topic,_se='';if($ctnfrm.length===0||!mode||(mode.search(/^(new|edit)[qac]$/)===-1)){return;}
if(!_abm.isOkForEdit(mode,msg_id,parent_id)){return;}
var regexp=/https?:\/\//g,url=_ct.urls.prefix+_url;if(regexp.exec(_ct.urls.prefix)===null&&typeof $data.domain!=='undefined'){url='https://'+$data.domain+url;}
_abm.gotoEditor(mode);_abm.toggleOvlDisplay(mode,'block',msg_id,parent_id);_se=(_ct._is._cur_star)?'&stareval='+_ct._is._cur_star:'';_ct._is._cur_star=false;ccm.common.dom.oldAjaxUpdater($ctnfrm,url,{method:'get',parameters:ccmBoxes.topic.getCommonPrms()+'&ID='+msg_id+'&mode='+mode+_se+'&redirectUrl='+encodeURIComponent(window.location.href),evalScripts:true,onComplete:function(){_abm.toggleEditor(mode,'block',msg_id,parent_id);_abm.toggleOvlDisplay(mode,'none',msg_id,parent_id);if(mode.indexOf('edit')!==-1){_abm.toggleDisplay(mode,'none',msg_id);}
_abm.finalizeEditor(mode,msg_id,parent_id);if(mode==='editq'){$(this).countTitle();}
$(this).checkNicknameAnon();$(this).checkEmailAnon();},onFailure:function(transport){_abm.toggleOvlDisplay(mode,'none',msg_id,parent_id);$ctnfrm.after('<div class="boxError">'+transport.responseText+'</div>');}});},submitFrm:function(mode,msg_id,parent_id,pview){pview=pview||false;var $ctnfrm=ccmBoxes.topic.abm.getFrmCtn(mode,msg_id,parent_id),_key='',_ct=ccmBoxes.topic;var messageArea=$ctnfrm[0].querySelector('textarea.jForumEditorTextarea');if(messageArea){messageArea.value=messageArea.value.replace(/\(\) {/g,'(){');}
if($ctnfrm.length===0||!mode||(mode.search(/^(new|edit)[qac]$/)===-1)){return;}
_key=((mode==='newc')||(mode==='editc'))?mode+msg_id:mode+'qa';if(!_ct.topicfrms[_key]){_ct.topicfrms[_key]=new ccmBoxes.topicfrm();}
_ct.topicfrms[_key].init(mode,msg_id,parent_id);_ct.topicfrms[_key].submit(pview);},reloadOri:function(mode,msg_id,parent_id){var _key=((mode==='newc')||(mode==='editc'))?mode+msg_id:mode+'qa',_ct=ccmBoxes.topic;if(!_ct.topicfrms[_key]||!_ct.topicfrms[_key]._pview){return;}
_ct.topicfrms[_key].init(mode,msg_id,parent_id);_ct.topicfrms[_key].reload();},toggleDisplay:function(mode,force,msg_id){var $el=null;switch(mode){case'editq':case'newq':$el=$('#quesfullctn');break;case'editc':case'edita':$el=$('#d'+msg_id);break;}
if($el!==null&&$el.length>0){$el.css('display',force);}},gotoEditor:function(mode){if(mode==="newa"){location.hash='#newanswer';}},finalizeEditor:function(mode,msg_id,parent_id){var _abm=ccmBoxes.topic.abm,$frm=_abm.getFrm(mode,msg_id),$message=$frm.find('textarea[name=message]'),_ct=ccmBoxes.topic,$el=null,_r,event=new Event('displayForumForm');if(_ct._is.titlefocus&&$frm.length>0&&typeof $frm.prop('titre')!=='undefined'){$frm.prop('titre').focus();}else if($frm.length>0&&$message.length>0){if((mode==='editc')||(mode==='newc')){(new ccm.common.dom.TaResize($message)).go();}
ccmBoxes.topic.initQafrmEvents($message);$message.trigger('focus');window.dispatchEvent(event);var replyContainer=$frm.closest('.jReplyContainer')[0];if(typeof replyContainer!=="undefined"){replyContainer.scrollIntoView(replyContainer.clientHeight>=screen.height);}
if((mode==='newa')||(mode==='newq')||(mode==='newc')){if($message[0].setSelectionRange){$message[0].setSelectionRange(0,0);}else if($message[0].createTextRange){_r=$message[0].createTextRange();_r.collapse(true);_r.moveEnd('character',0);_r.moveStart('character',0);_r.select();}}}
switch(mode){case'newc':case'newa':break;}},updateDisplay:function(mode,html,msg_id,parent_id,pview){switch(mode){case'newa':$('#a0').remove();$('#answers').append(html);break;case'newq':if(pview){$('#quesfullctn').html(html);}else{$('#topic_question').html(html);}
break;case'editq':$('#quesfullctn').html(html);break;case'newc':$('#c0').remove();var _ct=ccmBoxes.topic;var $container=$('#comments_'+parent_id);var $seeMore=$container.find('.jSeeMore').first();if($seeMore.length>0&&_ct.uforum.module!==undefined){$(html).insertBefore($seeMore);}else{for(var commentsChild of $container[0].childNodes){if(commentsChild.childElementCount===0){$container[0].removeChild(commentsChild);}}
$container.append(html);}
break;case'editc':case'edita':$('#d'+msg_id).html(html);break;}},gotoPview:function(mode){switch(mode){case'newq':case'editq':location.hash='#breadScrumb';break;}},finalyseUpdate:function(mode,msg_id,cat){var _ct=ccmBoxes.topic;if(mode==='newq'){_ct.question_id=msg_id;_ct.forum_id=cat;$('#ctn_0').attr('id','ctn_'+msg_id);$('#newanswer_0').attr('id','newanswer_'+msg_id);$('#content_ctn').removeClass('container');if(ccmBoxes.boxes.myinterv){ccmBoxes.boxes.myinterv.reload();}}}}};})(jQuery);(function($){"use strict";ccmBoxes.topicfrm=function(){return this;};ccmBoxes.topicfrm.prototype={msg_id:0,parent_id:0,mode:'',elts:{frm:null},_pview:false,init:function(mode,msg_id,parent_id){this.msg_id=msg_id;this.parent_id=parent_id;this.elts.frm=ccmBoxes.topic.abm.getFrm(mode,msg_id)[0];this.mode=mode;return self;},submit:function(pview){pview=pview||false;var _ct=ccmBoxes.topic,_abm=ccmBoxes.topic.abm,self=this;_abm.toggleOvlFrm(this.mode,'block',this.msg_id);if(this._fields_error){for(var i=0;i<this._fields_error.length;i++){$(this._fields_error[i]).removeClass('form_error_field');}}
$.ajax({url:_ct.urls.prefix+'postmsgfrm/',data:ccm.common.form.formToQueryString(this.elts.frm)+(pview?'&pview=1':'')+_ct.uforum.get_prms,type:'POST',success:function(data){if(pview){self._pview=true;}
_abm.toggleOvlFrm(self.mode,'none',self.msg_id);self.callbackOnSubmit(data,pview);$('#content_ctn .fancy').fancy();},error:function(data){_abm.toggleOvlFrm(self.mode,'none',self.msg_id);self.triggerError(data.responseText);}});return false;},reload:function(){var _ct=ccmBoxes.topic,_abm=ccmBoxes.topic.abm,self=this;$.ajax({url:_ct.urls.prefix+'shmsg/',data:ccm.common.form.formToQueryString(this.elts.frm)+_ct.uforum.get_prms,type:'POST',success:function(data){_abm.toggleOvlFrm(self.mode,'none',self.msg_id);ccmBoxes.topicfrm.prototype.callbackOnSubmit(data,false);},error:function(data){_abm.toggleOvlFrm(self.mode,'none',self.msg_id);this.triggerError(data.responseText);}});return false;},callbackOnSubmit:function(data,pview){var _s='',_key=null,_mode=data.mode,_msgs=data.msgs,_url=data.url,_html=data.html,_id=data.ID,_isNotif=parseInt(data.notif),_parentId=this.parent_id,_abm=ccmBoxes.topic.abm;$('#m'+this.mode+this.msg_id).css('display','none');if(data.res===false){this._fields_error=[];if(_msgs){for(var i=0;i<_msgs.length;i++){_key=_msgs[i][0];_s+='<li>'+((_msgs[i]instanceof Array)?_msgs[i][1]:_msgs[i])+'</li>';if(!this.elts.frm[_key]){continue;}
this._fields_error.push(this.elts.frm[_key]);$(this.elts.frm[_key]).addClass('form_error_field');}}
_s=(_s==='')?data.msg:'<ul class="disc">'+_s+'</ul>';this.triggerError(_s);return false;}
if(!pview){if(!_html||(_html==='')){window.location.href=window.location.href.replace(/#.*$/g,'')+'#p'+_id;}
if(_mode==='newq'&&_url){if(typeof $data.app==="undefined"||typeof $data.app.sns==="undefined"||Notification.permission==='denied'||!window.PushManager||_isNotif===0){window.location.href=_url;}
if(_isNotif!==0){window.dispatchEvent(new CustomEvent($.wonderpush.config.asynchroniousFollowingEvent,{detail:{tag:'forum-'+$data.domain+'-'+_id,redirectUrl:_url}}));}
return true;}
_abm.updateDisplay(_mode,_html,_id,_parentId,pview);_abm.closeFrm(_mode,_id,_parentId);_abm.finalyseUpdate(_mode,_id,data.cat);}else{_abm.updateDisplay(_mode,_html,_id,_parentId,pview);_abm.toggleDisplay(_mode,'block',_id);_abm.gotoPview(_mode);}
return true;},triggerError:function(msg,exception){var _id='m'+this.mode+this.msg_id,_ctnfrm=this.elts.frm,_s=msg+(exception?' ('+exception.message+')':''),$el=$("#"+_id);if($el.length===0){$el=$("<div id="+_id+"></div>");if(_ctnfrm){$el.insertBefore(_ctnfrm);}else{$el.appendTo(_ctnfrm);}}
ccmBoxes.topic.triggerErrorInEl($el,_s);}};ccmBoxes.topic.mod={place:function(event){var $ctnfrm=$('#modo_div_new'),$ctn=$('#oasLayout'),_cpos=0;if(typeof event==='string'){_cpos=event.indexOf(',');if(_cpos>=0){$ctnfrm.css({top:event.substring(0,_cpos)+'px',left:($ctn.offset().left+parseInt(event.substring(_cpos+1),10))+'px'});}else{var $shmodoquest=$("#shmodoquest");$ctnfrm.css({left:($shmodoquest.offset().left+$shmodoquest.width()+10)+'px',top:$shmodoquest.offset().top-15+'px'});}}else{$ctnfrm.css({top:((document.all)?event.clientY+document.documentElement.scrollTop:event.pageY)-27+'px',left:((document.all)?event.clientX+document.documentElement.scrollLeft:event.pageX)+18+'px'});}},load:function(msg_id,actid,callback,prms){var $ctnfrm=$('#modo_div_new'),_ct=ccmBoxes.topic,_frm,_prms;if($ctnfrm.length===0){return;}
_frm=$('#frmselactmod')[0];_prms=(_frm)?ccm.common.form.formToQueryString(_frm)+_ct.uforum.get_prms:ccmBoxes.topic.getCommonPrms()+'&ID='+msg_id+'&actid='+actid;if(prms){_prms+='&'+prms;}
ccmBoxes.topic.mod.toggleOvl($ctnfrm);$.ajax({url:_ct.urls.prefix+'shmodomenu/',data:_prms,type:'GET',success:function(data){ccmBoxes.topic.mod.toggleOvl($ctnfrm);$ctnfrm.html(data);ccmBoxes.topic.initModoEvents();if(actid==='solve'||actid==='addmyi'){ccmBoxes.topic.mod.submit(msg_id);}
typeof callback==="function"&&callback();},error:function(data){ccmBoxes.topic.mod.toggleOvl($ctnfrm);$ctnfrm.after('<div class="boxError">'+data.responseText+'</div>');}});},forceSignalement:function(msgId){msgId=parseInt(msgId,10);var $signalDiv=$('.jOpenSignalPopup[data-msgid="'+msgId+'"]');if($signalDiv.length>0){var offsetValues=$signalDiv.offset();$('html, body').animate({scrollTop:offsetValues.top-40,scrollLeft:offsetValues.left});$signalDiv.trigger('click');}},submit:function(){var $ctnfrm=$('#modo_div_new'),$frm=$('#frmactmod'),$modmsg=$("#modmsg"),_ct=ccmBoxes.topic;if($ctnfrm.length===0||$frm.length===0){return;}
ccmBoxes.topic.mod.toggleOvl($ctnfrm);$.ajax({url:_ct.urls.pmm,data:ccm.common.form.formToQueryString($frm)+_ct.uforum.get_prms,type:'POST',success:function(data){ccmBoxes.topic.mod.toggleOvl($ctnfrm);var dataOk=ccmBoxes.topic.checkJson(data,$modmsg);if(!dataOk){return;}
ccmBoxes.topic.triggerOkInEl($modmsg,data.msg);ccmBoxes.topic.reloadTopic.call(_ct);if(data.act==='addmyi'&&ccmBoxes.boxes.myinterv){ccmBoxes.boxes.myinterv.reload();}
setTimeout(function(){$ctnfrm.html('&nbsp;').hide();},1000);},error:function(data){ccmBoxes.topic.mod.toggleOvl($ctnfrm);ccmBoxes.topic.triggerErrorInEl($modmsg,data.responseText);}});},toggleOvl:function($ctn){var $el=$('#modo_ovl');if($el.length===0){$el=$('<div id="modo_ovl" class="overlayDiv waiting" style="display:none"></div>');$ctn.after($el);}
$el.toggle();}};$.fn.checkNicknameAnon=function(){var delayedCheckNickAnon=function(nick){$.ajax({url:'/forum/check_nickname_anon/',type:'POST',dataType:'json',data:{nick:nick},success:function(response){if(response.errorNick){if($('.jNickMessage').length){$('.jNickMessage').remove();}
$('.jCheckNickAnon').after('<div class="jNickMessage form_error_message">'+response.errorNick+'</div>');}else{$('.jNickMessage').remove();}},error:function(err){console.error('check nickname anon error: '+err);}})};$('.jCheckNickAnon').on('keyup',function(event){var nick=event.target.value;if(nick.length===0){$('.jNickMessage').remove();return;}
clearTimeout(this.timeout);var self=this,actualCall=function(){self.timeout=null;delayedCheckNickAnon(nick);};this.timeout=setTimeout(actualCall,500);});};$.fn.checkEmailAnon=function(){var delayedCheckEmail=function(email){$.ajax({url:'/register/check_email/',type:'POST',dataType:'json',data:{email:email},success:function(response){if(response.email){if(!$('.jEmailMessage').length){$('.jCheckEmailAnon').after('<div class="jEmailMessage form_error_message">'+response.email+'</div>');}}else{$('.jEmailMessage').remove();}},error:function(err){console.error('check email anon error: '+err);}})};$('.jCheckEmailAnon').on('keyup',function(event){var email=event.target.value;if(email.length===0){$('.jEmailMessage').remove();return;}
clearTimeout(this.timeout);var self=this,actualCall=function(){self.timeout=null;delayedCheckEmail(email);};this.timeout=setTimeout(actualCall,500);});};$.fn.scrollToElem=function($elem){var offset=0;if(window.window.innerWidth<1000){offset=60;}
$('html, body').animate({scrollTop:($elem.offset().top-offset)},0);}
$.fn.goToHash=function(hash){var anchor="",id='',list=[];if(hash.substring(1)==="dernier"){anchor='p'+$data.arboTopic.last_id;id=$data.arboTopic.last_id;list=$data.arboTopic.id;}else if(hash.substring(1).startsWith('p')){anchor=hash.substring(1);id=anchor.substring(1);list=$data.arboTopic.id;}else{anchor=hash.substring(1);id=hash.substring(1);list=$data.arboTopic.order;}
if($("a[name='"+anchor+"']").length===0){if(typeof list[id]!="undefined"){var $btn=$("#a"+list[id]+" .jSeeMorePoc button");if($btn.length>0){ccmBoxes.topic.seeMorePoc({target:$btn[0]},anchor,function(anchor){var $anchorElem=$("a[name='"+anchor+"']");if($anchorElem.length>0){$(this).scrollToElem($anchorElem);}});}}}};$(document).on('click','#jFormSearchOptionsClose a:first',function(){$('#searchOpt').css('display','none');});$(document).ready(function(){if(window.location.search&&window.location.search.match(/full/)){$('.jLoaderBouncing').addClass('loader-bouncing--display');ccmBoxes.topic.get_prms.full=true;ccmBoxes.topic.reloadTopic(true);}
if(typeof $data.arboTopic!=="undefined"){var hash=document.location.hash;if(hash){$(this).goToHash(hash);}
$(window).on('hashchange',function(){$(this).goToHash(document.location.hash);});}});})(jQuery);(function($)
{'use strict';$.fn.stick=function(options)
{options=$.extend({},$.fn.stick.defaultOptions,options);return this.each(function()
{var sticker=$(this),stickerPosition=null,stopStick=false,isSticked=false,optStickTo=sticker.data('stickto'),optStickPadding=sticker.data('stickpadding')||0,optStickThreshold=sticker.data('stickthreshold')||40,container=typeof optStickTo!=='undefined'?$(sticker.data('stickto')):sticker.parent(),windowPos=$(window).scrollTop(),offset=optStickPadding,STATES={containerTooSmall:0,atBottom:1,sticked:2,atTop:3},currentState=null,getPositionState=function(additionalOffset)
{if(stickerPosition===null){stickerPosition=sticker.offset();}
additionalOffset=additionalOffset||0;var stickerBottom=stickerPosition.top+sticker.height(),containerTop=container.offset().top,containerBottom=containerTop+container.height(),cssPosition=sticker.css('position'),testedOffset=offset+additionalOffset;if(containerBottom<=(stickerBottom+testedOffset+optStickThreshold))
{return STATES.containerTooSmall;}
else if(windowPos>=(stickerPosition.top-testedOffset))
{var containerBottomWithPad=containerTop+container.outerHeight(true);if(windowPos>(containerBottomWithPad-sticker.outerHeight(true)-(testedOffset*2)))
{return cssPosition!=='absolute'?STATES.atBottom:currentState;}
else if(cssPosition!=='fixed')
{return STATES.sticked;}
else
{return currentState;}}
else if(cssPosition!=='relative'&&cssPosition!=='')
{return STATES.atTop;}
else
{return currentState;}};this.setAttribute('data-stickenable',true);var handleAdsDockEvents=function(e)
{if(e.type==='ads.top.docked'){offset+=e.detail.nodeHeight;}
else if(e.type==='ads.top.undocked'){offset-=e.detail.nodeHeight;}
if(isSticked)
{sticker.css({transition:(parseInt(e.detail.delay,10)||0)+'ms ease-in-out',top:offset+'px'});sticker.one('transitionend',function(){sticker.css({transition:''});});}};window.addEventListener("ads.top.docked",handleAdsDockEvents);window.addEventListener("ads.top.undocked",handleAdsDockEvents);if(container.length){sticker.css({'max-width':sticker.width(),width:'100%'});$(window).on('scroll touchmove',function(event){if(stopStick===true){$(this).off(event);return;}
var newWindowPos=$(window).scrollTop();if(windowPos===newWindowPos){return;}
windowPos=newWindowPos;if(stickerPosition===null){stickerPosition=sticker.offset();}
var newState=getPositionState();if(currentState===newState)
{if(currentState===STATES.atTop)
{stickerPosition=sticker.offset();}
return;}
currentState=newState;switch(currentState){case STATES.containerTooSmall:stopStick=true;isSticked=false;sticker.css({position:'',top:''});break;case STATES.atBottom:isSticked=false;sticker.css({position:'absolute',top:'',bottom:offset+'px'});break;case STATES.sticked:isSticked=true;sticker.css({position:'fixed',top:offset+'px',bottom:''});break;case STATES.atTop:isSticked=false;sticker.css({position:'',top:''});stickerPosition=sticker.offset();break;}});}
this.isSticked=function(additionalOffset)
{return getPositionState(additionalOffset)===STATES.sticked;};this.getState=function()
{return currentState;};});};$.fn.stick.defaultOptions={};}(jQuery));