var myObject = {
    "hiHelloMonster": [{
        "mapaDeSitio": "<b>Mapa de sitio</b>",
        "fechaDePublicacion": "",
        "Post": "Codigos en https://codepen.io/hihellomonster/full/MWpNVEK",
        "pageid": "mapadesitio.html",
        "data-href": "/mapadesitio",
        "id": "animalesGlyps",
        "accion": "Ver Demo y Descargar",
        "nameGlyphs": "Animales",
        "version": "1.0",
        "ultimaActualizacion": "18-junio-2021",
        "classPrefix": "animal-",
        "metaDataURL": "https://hihello.monster/glyphs/animales/demo.html",
        "metaDataDescription": "Font Glyphs de animales para acelerar ... ",
        "metaDataCopyright": "hiHello.monster!",
        "metaDataDesigner": "Luis Angel Maciel",
        "metaDataDesignerURL": "https://hihello.monster/luisangelmaciel",
        "metaDataLicense": "GNU GPL 3.0",
        "metaDataLicenseURL": "https://www.gnu.org/licenses/gpl-3.0.html",
    }, {
        "mapaDeSitio": "Gliphys",
        "fechaDePublicacion": "Junio 20212",
        "Post": "Descarga los Glyphs de Animales-Glyphs!",
        "pageid": "mapadesitio.html",
        "data-href": "/glyphs/animales/demo.html",
        "id": "animalesGlyps",
        "accion": "Ver Demo y Descargar ",
        "nameGlyphs": "Animales",
        "version": "1.0",
        "ultimaActualizacion": "18-junio-2021",
        "classPrefix": "animal-",
        "metaDataURL": "https://hihello.monster/glyphs/animales/demo.html",
        "metaDataDescription": "Font Glyphs de animales para acelerar ... ",
        "metaDataCopyright": "hiHello.monster!",
        "metaDataDesigner": "Luis Angel Maciel",
        "metaDataDesignerURL": "https://hihello.monster/luisangelmaciel",
        "metaDataLicense": "GNU GPL 3.0",
        "metaDataLicenseURL": "https://www.gnu.org/licenses/gpl-3.0.html",
        "imgSgv": "./favicon.png",
        "hrefDemoGlyphs": "https://hihello.monster/glyphs/animales/demo.html",
        "postFoto1": "https://www.xiiber.com/img/photo-preview-01.png",
        "altPostFoto1": "Alt Post Foto 1",
        "postFoto2": "https://www.xiiber.com/img/photo-preview-02.png",
        "altPostFoto2": "Alt Post Foto 2",
        "postFoto3": "https://www.xiiber.com/img/photo-preview-03.png",
        "altPostFoto3": "Alt Post Foto 3",
        "postFoto4": "https://www.xiiber.com/img/photo-preview-00.png",
        "altPostFoto4": "Alt Post Foto 4",
    }, {
        "mapaDeSitio": "Templetes",
        "fechaDePublicacion": "16-agosto-2020",
        "Post": "Viajes",
        "pageid": "viajes.html",
        "data-href": "viajes",
        "id": "viajes",
        "accion": "Ver ahora",
        "fechaDePublicacion": "Junio 20212",
        "Post": "Animales-Glyphs!",
        "pageid": "mapadesitio.html",
        "data-href": "/glyphs/animales/demo.html",
        "id": "animalesGlyps",
        "accion": "Ver Demo y Descargar ",
        "nameGlyphs": "Animales",
        "version": "1.0",
        "ultimaActualizacion": "18-junio-2021",
        "classPrefix": "animal-",
        "metaDataURL": "https://hihello.monster/glyphs/animales/demo.html",
        "metaDataDescription": "Font Glyphs de animales para acelerar ... ",
        "metaDataCopyright": "hiHello.monster!",
        "metaDataDesigner": "Luis Angel Maciel",
        "metaDataDesignerURL": "https://hihello.monster/luisangelmaciel",
        "metaDataLicense": "GNU GPL 3.0",
        "metaDataLicenseURL": "https://www.gnu.org/licenses/gpl-3.0.html",
        "imgSgv": "./favicon.png",
        "hrefDemoGlyphs": "https://hihello.monster/glyphs/animales/demo.html",
        "postFoto1": "https://www.xiiber.com/img/photo-preview-01.png",
        "altPostFoto1": "Alt Post Foto 1",
        "postFoto2": "https://www.xiiber.com/img/photo-preview-02.png",
        "altPostFoto2": "Alt Post Foto 2",
        "postFoto3": "https://www.xiiber.com/img/photo-preview-03.png",
        "altPostFoto3": "Alt Post Foto 3",
        "postFoto4": "https://www.xiiber.com/img/photo-preview-00.png",
        "altPostFoto4": "Alt Post Foto 4",
    }, {
        "mapaDeSitio": "Templetes",
        "fechaDePublicacion": "16-agosto-2020",
        "Post": "Mapa de sitio",
        "pageid": "mapadesitio.html",
        "data-href": "mapadesitio",
        "id": "mapadesitio",
        "accion": "Ver ahora",
        "fechaDePublicacion": "Junio 20212",
        "Post": "Animales-Glyphs!",
        "pageid": "mapadesitio.html",
        "data-href": "/glyphs/animales/demo.html",
        "id": "animalesGlyps",
        "accion": "Ver Demo y Descargar ",
        "nameGlyphs": "Animales",
        "version": "1.0",
        "ultimaActualizacion": "18-junio-2021",
        "classPrefix": "animal-",
        "metaDataURL": "https://hihello.monster/glyphs/animales/demo.html",
        "metaDataDescription": "Font Glyphs de animales para acelerar ... ",
        "metaDataCopyright": "hiHello.monster!",
        "metaDataDesigner": "Luis Angel Maciel",
        "metaDataDesignerURL": "https://hihello.monster/luisangelmaciel",
        "metaDataLicense": "GNU GPL 3.0",
        "metaDataLicenseURL": "https://www.gnu.org/licenses/gpl-3.0.html",
        "imgSgv": "./favicon.png",
        "hrefDemoGlyphs": "https://hihello.monster/glyphs/animales/demo.html",
        "postFoto1": "https://www.xiiber.com/img/photo-preview-01.png",
        "altPostFoto1": "Alt Post Foto 1",
        "postFoto2": "https://www.xiiber.com/img/photo-preview-02.png",
        "altPostFoto2": "Alt Post Foto 2",
        "postFoto3": "https://www.xiiber.com/img/photo-preview-03.png",
        "altPostFoto3": "Alt Post Foto 3",
        "postFoto4": "https://www.xiiber.com/img/photo-preview-00.png",
        "altPostFoto4": "Alt Post Foto 4",
    }]
};

w3.displayObject("Post", myObject);
w3.displayObject("Glyphs", myObject);
w3.displayObject("siteMap", myObject);